


  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
	  - ./nginx/config.conf:/etc/nginx/conf.d/default.conf
      - ./${path_to_compiled_code}:/app:cached
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"; chown -R nginx:nginx /app;'"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    networks:
      - backend

networks:
  backend:
    name: ${projectName}

